import React, { useState } from 'react';
import '../styles/drivers.scss';

const AddVehicleDialog = ({ onClose, onSave }) => {
    const [vehicle, setVehicle] = useState({
        user_id: '', // This will be autogenerated or fetched from the user table
        vehicle_type: '',
        license_plate: '',
        availability: ''
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setVehicle(prev => ({ ...prev, [name]: value }));
    };

    const handleSubmit = () => {
        onSave(vehicle);
        onClose();
    };

    return (
        <div className="vehicle-dialog-overlay">
        <div className="vehicle-dialog">
            <button className="close-button" onClick={onClose}>X</button>
            <h3>Add Driver</h3>
            <label>
                Vehicle Type:
                <input type="text" name="vehicle_type" value={vehicle.vehicle_type} onChange={handleChange} />
            </label>
            <label>
                License Plate:
                <input type="text" name="license_plate" value={vehicle.license_plate} onChange={handleChange} />
            </label>
            <label>
                Availability:
                <input type="text" name="availability" value={vehicle.availability} onChange={handleChange} />
            </label>
            <button className="submit" onClick={handleSubmit}>Save</button>
        </div>
    </div>
    );
};

export default AddVehicleDialog;
